### ISSUE TITLE
removeFile did not remove file or throw errors.

### ISSUE THREAD

**Issue by Magicloud** [haskell/directory#12] opened 2014-12-23 08:59 UTC
In the following code, in `withTemp` function, after `removeFile fp`, the temp file was still there. I tried to use `try` to catch `IOException` that may throw by `removeFile`. I just got `Right ()`.

It is Ubuntu Trusty, ghc 7.8.3, directory 1.2.1.0.

```haskell
import Network.Curl
import System.Posix.Temp
import System.Directory
import System.IO
import Text.HTML.DOM
import Text.XML
import System.FilePath
import Control.Exception
 
type PostField = (String, String)
 
withTemp :: String -> (FilePath -> IO a) -> IO a
withTemp prefix f = do
  tmp <- getTemporaryDirectory
  (fp, h) <- mkstemp $ tmp </> prefix
  hClose h
  finally (f fp) $ removeFile fp
 
curl :: (CurlBuffer ty) => URLString -> Maybe [PostField] -> IO (Either CurlCode ty)
curl url values = do
  let mPf = fmap (map (\(k, v) -> k ++ "=" ++ v)) values
  (cc, ty) <- withTemp "Cookie" $ \tmp -> withCurlDo $
    let curlOpts_ = [ CurlHttpAuth [HttpAuthAny]
                    , CurlUserPwd ":"
                    , CurlCookieFile tmp
                    , CurlCookieJar tmp
                    , CurlFollowLocation True
                    , CurlUnrestrictedAuth True ]
        curlOpts = case mPf of
                     Nothing -> curlOpts_
                     Just pf -> (CurlPostFields pf) : curlOpts_
    in curlGetString_ url curlOpts
  return $ if cc == CurlOK
              then Right ty
              else Left cc
```

**Comment by hvr** [comment] 2015-01-16 16:24
I wonder if this is related to #4

**Comment by Rufflewind** [comment] 2015-02-18 03:03
I tried the test program and I don't believe the problem is related to *directory*.  The temporary file appears to be created asynchronously long after `removeFile` has completed.  There is a roughly 2 second delay before the file appears on my filesystem even though the function has completed execution.

**Comment by feuerbach** [comment] 2015-02-18 09:14
Why would the file be created asynchronously?

Anyway, I can't reproduce the issue on Fedora 21 with

``` haskell
main = curl "http://google.com" Nothing >>= (print :: Either CurlCode String -> IO ())
```

**Comment by Rufflewind** [comment] 2015-02-18 22:35
> Why would the file be created asynchronously?

I don't know.  Something odd about the curl library.  Perhaps `unsafeInterleaveIO`?  The problem couldn't be reproduced unless I forced the result to NF.

Polling the existence of the file at 1 sec intervals:

```
withTemp: does /tmp/CookieYcViim exist?  True
withTemp: file /tmp/CookieYcViim has been removed
main: does /tmp/CookieYcViim exist?  False
main: curl returned (truncated):
  Right "<!doctype html><html itemscope=\"\" itemtype=\"http://schema.org/WebPage\" lang=\"en\""
  Right 52318
main: does /tmp/CookieYcViim exist?  False
main: does /tmp/CookieYcViim exist?  True
main: does /tmp/CookieYcViim exist?  True
main: does /tmp/CookieYcViim exist?  True
```

Here's the code I used:

```hs
import Control.Concurrent
import Control.Monad
import Network.Curl
import System.Posix.Temp
import System.Directory
import System.IO
import System.FilePath
import Control.Exception

type PostField = (String, String)

withTemp :: String -> (FilePath -> IO a) -> IO a
withTemp prefix f = do
  tmp <- getTemporaryDirectory
  (fp, h) <- mkstemp $ tmp </> prefix
  hClose h
  finally (f fp) $ do
    putStr ("withTemp: does " ++ fp ++ " exist?  ")
    print =<< doesFileExist fp
    threadDelay 1000000
    removeFile fp
    putStrLn ("withTemp: file " ++ fp ++ " has been removed")

curl :: URLString -> Maybe [PostField] -> IO (FilePath, Either CurlCode String)
curl url values = do
  let mPf = fmap (map (\(k, v) -> k ++ "=" ++ v)) values
  (tmp, (cc, ty)) <- withTemp "Cookie" $ \tmp -> fmap (\x -> (tmp, x)) $ withCurlDo $
    let curlOpts_ = [ CurlHttpAuth [HttpAuthAny]
                    , CurlUserPwd ":"
                    , CurlCookieFile tmp
                    , CurlCookieJar tmp
                    , CurlFollowLocation True
                    , CurlUnrestrictedAuth True ]
        curlOpts = case mPf of
                     Nothing -> curlOpts_
                     Just pf -> (CurlPostFields pf) : curlOpts_
    in curlGetString_ url curlOpts
  return $ (,) tmp $ if cc == CurlOK
              then Right ty
              else Left cc

main :: IO ()
main = do
  (path, result) <- curl "http://google.com" Nothing

  putStr ("main: does " ++ path ++ " exist?  ")
  print =<< doesFileExist path
  threadDelay 1000000

  putStr "main: curl returned (truncated):\n  "
  print (take 80 `fmap` result)
  putStr "  "
  print (length `fmap` result) -- must force result to NF completely!

  forever $ do
    putStr ("main: does " ++ path ++ " exist?  ")
    print =<< doesFileExist path
    threadDelay 1000000
```

**Comment by argiopetech** [comment] 2015-02-18 22:54
Seeing as how this is a "can't fix, won't fix", is there a compelling reason to keep it open?

**Comment by Rufflewind** [comment] 2015-02-18 23:18
I left it open to see if anyone else has any comments.

**Comment by feuerbach** [comment] 2015-02-19 09:35
@Rufflewind thanks for the test case, but again, I can't reproduce it. On my system, it never gets to True for the second time.

**Comment by Rufflewind** [comment] 2015-02-19 18:20
@feuerbach I'm using a slightly different version of GHC (7.8.4) but I doubt that's the source of the problem. Mind if I ask what version of *libcurl* and *curl* you use?  I use curl-1.3.8 and libcurl-4.3.0.

**Comment by feuerbach** [comment] 2015-02-19 19:24
curl 1.3.8.1, libcurl 7.37.0

**Comment by Rufflewind** [comment] 2015-02-19 21:59
Hrm, I'm not sure what the problem is.  I built and linked against curl-7.37.0 and the test case still works for me.  Furthermore, curl-1.3.8.1 looks virtually identical to curl-1.3.8 modulo some documentation changes and a version bump.

**Closed** 2015-02-21 07:42 UTC
Labels: invalid
