### ISSUE TITLE
`directory-1.3.8.0` violates the Haskell PVP

### ISSUE THREAD

**Issue by andreasabel** [haskell/directory#147] opened 2022-11-19 15:23 UTC
From the `directory-1.3.8.0` CHANGELOG:
> Modules in directory are no longer considered [Safe](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/safe_haskell.html) because the `System.OsPath` dependency is no longer `Safe`.

This means that all packages that use `directory < 1.4` and `import safe System.Directory` are broken.  

In the wild, this looks like this:
```
Building library for MissingH-1.5.0.1..
...
src/Network/Email/Sendmail.hs:35:1: error:
    System.Directory: Can't be safely imported!
    The module itself isn't safe.
   |
35 | import safe System.Directory
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
Error: cabal: Failed to build MissingH-1.5.0.1
```

Standard action path:
- deprecate `directory-1.3.8.0` on hackage
- revise it to become unbuildable
- release as `directory-1.4`

ATTN: @Rufflewind

**Comment by Rufflewind** [comment] 2022-11-19 20:07
@bgamari @hasufell `System.OsPath` is not Safe and so `directory` transitively also became non-Safe. @andreasabel considers this a PVP violation, which leaves us with two options:

1. Restore the Safe status in `System.OsPath`, send out a minor release of filepath, and then mark filepath-1.4.100.0 as deprecated; or

2. Retain the non-Safe status quo, send out a major release of directory-1.4.0.0, and then mark directory-1.3.8.0 as deprecated.

Any thoughts on which approach to take?

**Comment by hasufell** [comment] 2022-11-20 03:34
I feel the specification is not very clear on that matter

https://pvp.haskell.org/

@Bodigrim 

I personally think that "doesn't compile without code change" is not really what non-breaking or "other" changes from PVP spec demand.

Then again, if you consider it part of the API, then you could argue different. The spec only implicitly defines "API".

**Comment by andreasabel** [comment] 2022-11-20 08:59
I agree that the PVP does not mention anything on safe vs. non-safe.  While nothing violates the _letter_ of the PVP, certainly going from safe to unsafe violates the _spirit_ of the PVP.  
The spirit (and dominant practice) is that it is _sufficient to set a major version upper bound_ for your dependencies (with some exceptions, e.g. when you define orphan instances).  So, if you make changes to your package that can break downstream packages, you need to bump the major version.

**Comment by hasufell** [comment] 2022-11-20 09:40
This would mean filepath itself also needs a major version bump. This is what I initially planned to do, but GHC team said that will create more work for them.

@bgamari @mpickering

**Comment by Bodigrim** [comment] 2022-11-20 10:44
There is a never ending trail of destruction caused by Safe Haskell. Friends do not let friends use `{-# Safe #-}`. I’m very serious, please just don’t.

**Comment by andreasabel** [comment] 2022-11-20 15:58
> Friends do not let friends use `{-# Safe #-}`.

This message should go to the haskell-language-server folks, summoning @jneira.
In my case (`MissingH`) the `safe` imports were added (Feb 2022) by the HLS tactic that creates explicit import lists (a terribly useful tool otherwise, maybe this is a flaw).

The GHC crowd seems rather undecided what to do with `SafeHaskell`, e.g. see this unresolved issue from 2014: https://gitlab.haskell.org/ghc/ghc/-/issues/8745

**Comment by Bodigrim** [comment] 2022-11-20 19:23
I suggest both `directory` and `MIssingH` to remove `Safe` pragmas. This is a misfeature which makes everything too fragile.

Bumping major versions of `filepath` and `directory` is an extremely costly change for the ecosystem. According to the letter of PVP they are not in breach, and my opinion is that it's Safe Haskell as a feature who is at fault with PVP here. There are only handful users of Safe Haskell, and it seems less costly to revise them by adding `directory < 1.3.8.0` bound.

**Comment by andreasabel** [comment] 2022-11-20 22:50
Serokell hackage serach for [`import safe System.Directory`](https://hackage-search.serokell.io/?q=import%5Cs%2Bsafe%5Cs%2BSystem%5C.Directory) only finds `MissingH`.  Fringe use indeed, and I only started the `import safe` thing because HLS suggested it (didn't even know about this syntax).

> ... `MIssingH` to remove `Safe` pragmas.

Will do, seems the most pragmatic course of action.

**Comment by andreasabel** [comment] 2022-11-21 07:34
> Serokell hackage search for [`import safe System.Directory`](https://hackage-search.serokell.io/?q=import%5Cs%2Bsafe%5Cs%2BSystem%5C.Directory) only finds `MissingH`.

Actually, I overlooked [`lio-fs`](https://hackage.haskell.org/package/lio-fs) which is a (likely academic) security library so they crucially rely on SafeHaskell.  I revised their packages to `directory < 1.3.8`:
- https://github.com/PLSysSec/lio/issues/56

> In my case (`MissingH`) the `safe` imports were added (Feb 2022) by the HLS tactic that creates explicit import lists (a terribly useful tool otherwise, maybe this is a flaw).

I might have been unjust in my assessment here because I misremembered. HLS only adds `safe` to `import` when the importing module is declared `Safe` ([see my relevant commit to `MissingH`](https://github.com/haskell-hvr/missingh/commit/1aa173e2f1e83af02d63e7d5f9c7742409371457)).  So, my apologies to the HLS developers, their logic is correct.

**Comment by mpickering** [comment] 2022-12-17 18:38
> This would mean filepath itself also needs a major version bump. This is what I initially planned to do, but GHC team said that will create more work for them.

My understanding is that `System.OsPath` is a new module, so that a minor bump is still fine for `filepath`. 

The issue here seems to be that `System.Directory` (an existing module) changes its safety status, I agree with @Bodigrim that removing the use of `SafeHaskell` is the best thing to do..

Thanks everyone for the discussion about this.

**Comment by andreasabel** [comment] 2023-01-14 20:47
For package `MissingH`, I am dropping `LANGUAGE Safe` for all modules importing `System.Directory` in this PR:
- https://github.com/haskell-hvr/missingh/pull/63

**Comment by Rufflewind** [comment] 2023-06-10 21:11
Are there any outstanding issues that remain here?

If not I will close this. Thank you all for the discussions.

**Closed** 2023-06-11 09:27 UTC
Labels: type: b-discussion
